version: '3.6'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    container_name: db
    ports:
      - 5432:5432
  app:
    image: ricardo/transactions
    build:
      context: ../../docker
      dockerfile: Dockerfile
    container_name: "application"
    env_file:
      - app.env
    ports:
      - 8080:8080
    depends_on:
      - db