version: '3.6'
services:
  transactions_db:
    image: postgres
    env_file:
      - db.env
    container_name: transactions_db
    ports:
      - 5432:5432
  transactions_application:
    image: ricardo/transactions
    build:
      context: ./../../../
      dockerfile: Dockerfile
    container_name: transactions_application
    env_file:
      - app.env
    ports:
      - 8080:8080
    depends_on:
      - transactions_db